# Подключаем настройки из отдельного файла
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  config:
    import: classpath:application-db.properties

  # Настройка Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Настройка JPA
  jpa:
    hibernate:
      ddl-auto: validate   # Проверяем, что схема совпадает с миграциями
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: INFO