# Подключаем настройки из отдельного файла
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  config:
    import: classpath:application-db.properties

  # Настройка Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Настройка JPA
  jpa:
    hibernate:
      ddl-auto: validate   # Проверяем, что схема совпадает с миграциями
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
  # Добавляем описание безопасности
  security:
    - name: Bearer Authentication
      type: http
      scheme: bearer
      bearer-format: JWT
      description: Введите токен в формате **Bearer {token}**